FROM node:15.5.0-buster-slim as builder

WORKDIR /app 

COPY package.json package-lock.json ./
RUN npm install --production

COPY . .

RUN npm run build


FROM nginx:1.19.7-alpine

WORKDIR /app

COPY --from=builder /app/build .

COPY nginx.conf /etc/nginx/conf.d/default.conf
